name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - folium=0.11.0
  - fsspec=0.8.3=py_0
  - geopy=2.0.0=pyh9f0ad1d_0
  - hvplot=0.6.0=py_1
  - intake=0.6.0=py_0
  - intake-esm=2020.8.15=py_0
  - ipywidgets=7.5.1=py_1
  - numpy=1.19.1
  - pandas=1.1.3=py38he6710b0_0
  - xarray=0.16.1=py_0
  - zarr=2.5.0=py_0
